_core:
  default_config_hash: IgOVnECx6lbVt6JVFnadoEEugneDf3UblPZnOzov43Q
mode: simple
ignored_config_entities:
  - block.block.sociallinks
  - 'poniintra_theme.settings:basic_page_structure'
  - 'poniintra_theme.settings:facebook_profile_url'
  - 'poniintra_theme.settings:instagram_profile_url'
  - 'poniintra_theme.settings:linkedin_profile_url'
  - 'poniintra_theme.settings:pinterest_profile_url'
  - 'poniintra_theme.settings:twitter_profile_url'
  - 'poniintra_theme.settings:youtube_profile_url'
