features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 0
  path: sites/poniintra/themes/poniintra_theme/images/logo.png
favicon:
  use_default: 1
